### ISSUE TITLE
external storage: ext* partitions fail on microSD

### ISSUE THREAD

**Issue by ben-en** [Outernet-Project/lighthouse-firmware#6] opened 2015-11-04 22:13 UTC
When the drive is plugged in it is acknowledged (see syslogs below), an error occurs, and regular
usage of internal storage is as it would be expected without external storage.

ext4 - microSD - on plug

```
Nov  4 21:19:01 outernet user.warn kernel: [ 3913.478572@0] normal card in
Nov  4 21:19:02 outernet user.info kernel: [ 3913.977398@0] sd: mmc_rescan_try_freq: trying to init card at 400000 Hz
Nov  4 21:19:02 outernet user.info kernel: [ 3914.172562@0] sd: new high speed SDHC card at address e624, clock 50000000, 4-bit-bus-width
Nov  4 21:19:02 outernet user.info kernel: [ 3914.180168@0] mmcblk0: sd:e624 SU04G 3.69 GiB 
Nov  4 21:19:02 outernet user.info kernel: [ 3914.196551@0]  mmcblk0: p1
Nov  4 21:19:03 outernet user.debug hotplug.mmcblk0p1: Checking filesystem using /usr/sbin/fsck.ext4
Nov  4 21:19:03 outernet user.debug hotplug.mmcblk0p1: Mounting /dev/mmcblk0p1 -> /mnt/mmcblk0p1
Nov  4 21:19:03 outernet user.warn kernel: [ 3915.046035@1] force enable DISCARD here for ext4 fs
Nov  4 21:19:03 outernet user.info hotplug.mmcblk0p1: /dev/mmcblk0p1 mounted at /mnt/mmcblk0p1
Nov  4 21:19:03 outernet user.debug hotplug.mmcblk0p1: Processing external storage
Nov  4 21:19:03 outernet user.warn kernel: [ 3915.057752@1] checked enable EXT4 DISCARD here
Nov  4 21:19:03 outernet user.warn kernel: [ 3915.057768@1] EXT4-fs (mmcblk0p1): mounting with "discard" option, but the device does not support discard
Nov  4 21:19:03 outernet user.info kernel: [ 3915.057776@1] EXT4-fs (mmcblk0p1): mounted filesystem with ordered data mode. Opts: (null)
Nov  4 21:19:06 outernet user.debug hotplug.mmcblk0p1: External storage platform is: (none)
Nov  4 21:19:06 outernet user.debug hotplug.mmcblk0p1: Preparing for external storage use
Nov  4 21:19:06 outernet user.debug hotplug.mmcblk0p1: Stopping services
Nov  4 21:19:06 outernet user.debug hotplug.mmcblk0p1: Stoppnig S91librarian
Nov  4 21:19:06 outernet user.debug hotplug.mmcblk0p1: Stoppnig S90fsal
Nov  4 21:19:06 outernet user.debug hotplug.mmcblk0p1: Stoppnig S80ondd
Nov  4 21:19:06 outernet user.info kernel: [ 3918.521421@1] wetek-dvb dvb.8: stop_feed_dmx0
Nov  4 21:19:06 outernet user.info kernel: [ 3918.521446@1] wetek-dvb dvb.8: FLUSH FIFO0
Nov  4 21:19:06 outernet user.info kernel: [ 3918.521456@1] wetek-dvb dvb.8: FLUSH ok
Nov  4 21:19:08 outernet user.err wptdm[1169]: request failed: 409
Nov  4 21:19:09 outernet user.debug hotplug.mmcblk0p1: Services stopped
Nov  4 21:19:09 outernet user.debug hotplug.mmcblk0p1: Initializing external storage
Nov  4 21:19:09 outernet user.debug hotplug.mmcblk0p1: Writing platform file to external storage
Nov  4 21:19:09 outernet user.debug hotplug.mmcblk0p1: Copying content from internal storage to external
Nov  4 21:19:09 outernet user.debug hotplug.mmcblk0p1: Copying /mnt/data/downloads/* -> /mnt/mmcblk0p1
Nov  4 21:19:09 outernet user.warn hotplug.mmcblk0p1: There were errors during copying
Nov  4 21:19:09 outernet user.info hotplug.mmcblk0p1: Using /dev/mmcblk0p1 as external storage
Nov  4 21:19:09 outernet user.debug hotplug.mmcblk0p1: Restarting services
Nov  4 21:19:10 outernet user.info ondd[1612]: [main] v2.1.0
Nov  4 21:19:10 outernet user.info ondd[1612]: [main] tuning to 1179 Mhz 22000 KSym
Nov  4 21:19:10 outernet user.debug hotplug.mmcblk0p1: Services started
Nov  4 21:19:10 outernet user.err hotplug.mmcblk0p1: ERROR: 'ext4'
```

ext4 - microSD - on remove

```
Nov  4 21:22:40 outernet user.warn kernel: [ 4131.899669@0] card out
Nov  4 21:22:40 outernet user.info kernel: [ 4131.908685@0] sd: card e624 removed
Nov  4 21:22:40 outernet user.debug hotplug.mmcblk0p1: Stopping services
Nov  4 21:22:40 outernet user.debug hotplug.mmcblk0p1: Stoppnig S91librarian
Nov  4 21:22:40 outernet user.debug hotplug.mmcblk0p1: Stoppnig S90fsal
Nov  4 21:22:40 outernet user.debug hotplug.mmcblk0p1: Stoppnig S80ondd
Nov  4 21:22:40 outernet user.info kernel: [ 4132.319804@0] wetek-dvb dvb.8: stop_feed_dmx0
Nov  4 21:22:40 outernet user.info kernel: [ 4132.319828@0] wetek-dvb dvb.8: FLUSH FIFO0
Nov  4 21:22:40 outernet user.info kernel: [ 4132.319837@0] wetek-dvb dvb.8: FLUSH ok
Nov  4 21:22:43 outernet user.debug hotplug.mmcblk0p1: Services stopped
Nov  4 21:22:43 outernet user.debug hotplug.mmcblk0p1: Restarting services
Nov  4 21:22:43 outernet user.info ondd[1656]: [main] v2.1.0
Nov  4 21:22:43 outernet user.info ondd[1656]: [main] tuning to 1179 Mhz 22000 KSym
Nov  4 21:22:43 outernet user.debug hotplug.mmcblk0p1: Services started
Nov  4 21:22:43 outernet user.err hotplug.mmcblk0p1: ERROR: Failed to unmount /dev/mmcblk0p1 (EXT_store)
```

ext3 - microSD - on plug

```
Nov  4 21:27:34 outernet user.warn kernel: [ 4426.414086@0] normal card in
Nov  4 21:27:35 outernet user.info kernel: [ 4426.907586@0] sd: mmc_rescan_try_freq: trying to init card at 400000 Hz
Nov  4 21:27:35 outernet user.info kernel: [ 4427.127668@0] sd: new high speed SDHC card at address e624, clock 50000000, 4-bit-bus-width
Nov  4 21:27:35 outernet user.info kernel: [ 4427.129048@0] mmcblk0: sd:e624 SU04G 3.69 GiB 
Nov  4 21:27:35 outernet user.info kernel: [ 4427.135572@0]  mmcblk0: p1
Nov  4 21:27:35 outernet user.err kernel: [ 4427.388445@0] mmcblk0: r/w command failed, status = 0x80000b00
Nov  4 21:27:35 outernet user.err kernel: [ 4427.388644@0] end_request: I/O error, dev mmcblk0, sector 7744496
Nov  4 21:27:35 outernet user.err kernel: [ 4427.388852@0] Buffer I/O error on device mmcblk0p1, logical block 967806
Nov  4 21:27:35 outernet user.err kernel: [ 4427.393031@0] mmcblk0: r/w command failed, status = 0x80000b00
Nov  4 21:27:35 outernet user.err kernel: [ 4427.393168@0] mmc_blk_reset 938 reset error md->reset_done:1 and type:1
Nov  4 21:27:35 outernet user.err kernel: [ 4427.393290@0] end_request: I/O error, dev mmcblk0, sector 7744496
Nov  4 21:27:35 outernet user.err kernel: [ 4427.393470@0] Buffer I/O error on device mmcblk0p1, logical block 967806
Nov  4 21:27:35 outernet user.debug hotplug.mmcblk0p1: Partition usage is None and cannot be used.
```

ext3 - microSD - on remove

```
Nov  4 21:36:30 outernet user.warn kernel: [ 4962.496522@0] card out
Nov  4 21:36:30 outernet user.info kernel: [ 4962.498060@1] sd: card e624 removed
Nov  4 21:36:30 outernet user.debug hotplug.mmcblk0p1: Partition usage is None and cannot be used.
```

ext2 - microSD - on plug

```
Nov  4 21:42:42 outernet user.warn kernel: [ 5333.818914@1] normal card in
Nov  4 21:42:42 outernet user.info kernel: [ 5334.317274@1] sd: mmc_rescan_try_freq: trying to init card at 400000 Hz
Nov  4 21:42:42 outernet user.info kernel: [ 5334.521607@0] sd: new high speed SDHC card at address e624, clock 50000000, 4-bit-bus-width
Nov  4 21:42:42 outernet user.info kernel: [ 5334.526768@0] mmcblk0: sd:e624 SU04G 3.69 GiB 
Nov  4 21:42:42 outernet user.info kernel: [ 5334.542438@0]  mmcblk0: p1
Nov  4 21:42:42 outernet user.err kernel: [ 5334.616492@0] mmcblk0: r/w command failed, status = 0x80000b00
Nov  4 21:42:42 outernet user.err kernel: [ 5334.616709@0] end_request: I/O error, dev mmcblk0, sector 7744496
Nov  4 21:42:42 outernet user.err kernel: [ 5334.616865@0] Buffer I/O error on device mmcblk0, logical block 968062
Nov  4 21:42:42 outernet user.err kernel: [ 5334.623523@0] mmcblk0: r/w command failed, status = 0x80000b00
Nov  4 21:42:42 outernet user.err kernel: [ 5334.623711@0] mmc_blk_reset 938 reset error md->reset_done:1 and type:1
Nov  4 21:42:42 outernet user.err kernel: [ 5334.623838@0] end_request: I/O error, dev mmcblk0, sector 7744496
Nov  4 21:42:42 outernet user.err kernel: [ 5334.623989@0] Buffer I/O error on device mmcblk0, logical block 968062
Nov  4 21:42:42 outernet user.err kernel: [ 5334.705948@0] mmcblk0: r/w command failed, status = 0x80000b00
Nov  4 21:42:42 outernet user.err kernel: [ 5334.706136@0] end_request: I/O error, dev mmcblk0, sector 7744496
Nov  4 21:42:42 outernet user.err kernel: [ 5334.706298@0] Buffer I/O error on device mmcblk0p1, logical block 967806
Nov  4 21:42:42 outernet user.err kernel: [ 5334.711555@0] mmcblk0: r/w command failed, status = 0x80000b00
Nov  4 21:42:42 outernet user.err kernel: [ 5334.711718@0] mmc_blk_reset 938 reset error md->reset_done:1 and type:1
Nov  4 21:42:42 outernet user.err kernel: [ 5334.711849@0] end_request: I/O error, dev mmcblk0, sector 7744496
Nov  4 21:42:42 outernet user.err kernel: [ 5334.712003@0] Buffer I/O error on device mmcblk0p1, logical block 967806
Nov  4 21:42:43 outernet user.debug hotplug.mmcblk0p1: Partition usage is None and cannot be used.
```

ext2 - microSD - on remove

```
Nov  4 22:00:40 outernet user.warn kernel: [ 6412.675478@0] card out
Nov  4 22:00:40 outernet user.info kernel: [ 6412.677909@1] sd: card e624 removed
Nov  4 22:00:41 outernet user.debug hotplug.mmcblk0p1: Partition usage is None and cannot be used.
```

**Comment by foxbunny** [comment] 2015-11-04 22:16
Dupe of #5

**Comment by ben-en** [comment] 2015-11-04 22:16
It's actually for a different device type.

edit: ack'd

**Comment by ben-en** [comment] 2015-11-04 23:05
microSD syslog output from ext\* is confirmed unrelated to previous NTFS flashing, just verified with a second card.

**Comment by ben-en** [comment] 2015-11-05 17:56
microSD cards still show the same information in syslog and do not work with ext\* partitions. Reopening because external hard drives do work with ext\* partitions, and therefore it is no longer a duplicate.

**Comment by foxbunny** [comment] 2015-11-06 11:41
@ben-en Please update with partition layout of the SD card.

**Comment by ben-en** [comment] 2015-11-06 15:33
Card was improperly formatted. The partition type according to the partition table was NTFS, which was obviously incorrect. According to syslog and `/proc/mounts` the microSD card has successfully mounted with ext4. Would you like me to test ext2/3 branko? It is certain that they also were labelled as NTFS by the partition table.

syslog:
```Nov  6 15:27:47 outernet user.warn kernel: [62777.624499@1] normal card in
Nov  6 15:27:47 outernet user.info kernel: [62778.117436@1] sd: mmc_rescan_try_freq: trying to init card at 400000 Hz
Nov  6 15:27:47 outernet user.info kernel: [62778.302097@1] sd: new high speed SDHC card at address e624, clock 50000000, 4-bit-bus-width
Nov  6 15:27:47 outernet user.info kernel: [62778.305480@1] mmcblk0: sd:e624 SU04G 3.69 GiB 
Nov  6 15:27:47 outernet user.info kernel: [62778.314006@1]  mmcblk0: p1
Nov  6 15:27:48 outernet user.debug hotplug.mmcblk0p1: Checking filesystem using /usr/sbin/fsck.ext4
Nov  6 15:27:48 outernet user.debug hotplug.mmcblk0p1: Mounting /dev/mmcblk0p1 -> /mnt/mmcblk0p1
Nov  6 15:27:48 outernet user.warn kernel: [62779.201664@1] force enable DISCARD here for ext4 fs
Nov  6 15:27:48 outernet user.info hotplug.mmcblk0p1: /dev/mmcblk0p1 mounted at /mnt/mmcblk0p1
Nov  6 15:27:48 outernet user.debug hotplug.mmcblk0p1: Processing external storage
Nov  6 15:27:48 outernet user.warn kernel: [62779.213636@1] checked enable EXT4 DISCARD here
Nov  6 15:27:48 outernet user.warn kernel: [62779.213652@1] EXT4-fs (mmcblk0p1): mounting with "discard" option, but the device does not support discard
Nov  6 15:27:48 outernet user.info kernel: [62779.213660@1] EXT4-fs (mmcblk0p1): mounted filesystem with ordered data mode. Opts: (null)
Nov  6 15:27:51 outernet user.debug hotplug.mmcblk0p1: External storage platform is: (none)
Nov  6 15:27:51 outernet user.debug hotplug.mmcblk0p1: Preparing for external storage use
Nov  6 15:27:51 outernet user.debug hotplug.mmcblk0p1: Stopping services
Nov  6 15:27:51 outernet user.debug hotplug.mmcblk0p1: Stoppnig S91librarian
Nov  6 15:27:51 outernet user.debug hotplug.mmcblk0p1: Stoppnig S90fsal
Nov  6 15:27:51 outernet user.debug hotplug.mmcblk0p1: Stoppnig S80ondd
Nov  6 15:27:51 outernet user.info kernel: [62782.525504@0] wetek-dvb dvb.8: stop_feed_dmx0
Nov  6 15:27:51 outernet user.info kernel: [62782.525525@0] wetek-dvb dvb.8: FLUSH FIFO0
Nov  6 15:27:51 outernet user.info kernel: [62782.525535@0] wetek-dvb dvb.8: FLUSH ok
Nov  6 15:27:54 outernet user.debug hotplug.mmcblk0p1: Services stopped
Nov  6 15:27:54 outernet user.debug hotplug.mmcblk0p1: Initializing external storage
Nov  6 15:27:54 outernet user.debug hotplug.mmcblk0p1: Writing platform file to external storage
Nov  6 15:27:54 outernet user.debug hotplug.mmcblk0p1: Copying content from internal storage to external
Nov  6 15:27:54 outernet user.debug hotplug.mmcblk0p1: Copying /mnt/data/downloads/\* -> /mnt/mmcblk0p1
Nov  6 15:27:55 outernet user.debug hotplug.mmcblk0p1: 
Nov  6 15:27:55 outernet user.info hotplug.mmcblk0p1: Using /dev/mmcblk0p1 as external storage
Nov  6 15:28:06 outernet user.warn kernel: [62797.237797@0] force enable DISCARD here for ext4 fs
Nov  6 15:28:06 outernet user.debug hotplug.mmcblk0p1: Restarting services
Nov  6 15:28:06 outernet user.warn kernel: [62797.258538@0] checked enable EXT4 DISCARD here
Nov  6 15:28:06 outernet user.warn kernel: [62797.258555@0] EXT4-fs (mmcblk0p1): mounting with "discard" option, but the device does not support discard
Nov  6 15:28:06 outernet user.info kernel: [62797.258564@0] EXT4-fs (mmcblk0p1): mounted filesystem with ordered data mode. Opts: (null)
Nov  6 15:28:06 outernet user.info ondd[1430]: [main] v2.1.0
Nov  6 15:28:06 outernet user.info ondd[1430]: [main] tuning to 1179 Mhz 22000 KSym
Nov  6 15:28:06 outernet user.debug hotplug.mmcblk0p1: Services started

``````

/proc/mounts:
```outernet@outernet:~$ cat /proc/mounts 
rootfs / rootfs rw 0 0
devtmpfs /dev devtmpfs rw,relatime,size=438020k,nr_inodes=109505,mode=755 0 0
ubi0:rootfs /mnt/rootfs ubifs ro,relatime 0 0
tmpfs /mnt/tmpfs tmpfs rw,relatime,size=65536k 0 0
unionfs / unionfs rw,relatime,dirs=/mnt/tmpfs=rw:/mnt/rootfs=ro 0 0
proc /proc proc rw,relatime 0 0
sysfs /sys sysfs rw,relatime 0 0
none /sys/kernel/debug debugfs rw,relatime 0 0
devpts /dev/pts devpts rw,relatime,gid=5,mode=620 0 0
ubi0:persist /mnt/persist ubifs rw,noatime 0 0
ubi0:data /mnt/data ubifs rw,noatime 0 0
/dev/mmcblk0p1 /mnt/data/downloads ext4 rw,relatime,data=ordered 0 0
``````

**Comment by foxbunny** [comment] 2015-11-06 15:35
Looks good

**Closed as completed by foxbunny** 2015-11-06 15:35 UTC
Labels: bug
